version: '3.8'
services:
  mlflow_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata_mlflow:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow_server:
    build: .
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_DB_URI}
    depends_on:
      - mlflow_db
    command: >
      bash -c "sleep 10 && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri ${MLFLOW_DB_URI}"

volumes:
  pgdata_mlflow:
